#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  gpg-connect-agent killagent /bye
  gpg-connect-agent /bye

  git config --global credential.helper osxkeychain
else
  # install ubuntu packages
  sudo apt install -y $(grep -vE "^\s*#" ~/packages  | tr "\n" " ")

  # install flatpacks
  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  flatpak install https://downloads.1password.com/linux/flatpak/1Password.flatpakref
  for i in `cat ~/flatpacks`; do flatpak install --user -y flathub $i; done;

  # install asdf
  if [ ! -d "$HOME/.asdf" ]; then
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  fi

  # reload gnome config
  # dconf load / < "$HOME/.config/dconf/settings.ini"
fi

# use zsh shell
echo "Changing shell"
chsh -s /usr/bin/zsh

# Directory to look for bootstrap executables in
BOOTSTRAP_D="${BASH_SOURCE[0]}.d"

if [[ ! -d "$BOOTSTRAP_D" ]]; then
    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
    exit 1
fi

find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
        if ! "$bootstrap"; then
            echo "Error: bootstrap '$bootstrap' failed" >&2
            exit 1
        fi
    fi
done

# install nix
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install

# enter the nix environment
. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

# bootstrap nix
nix run nixpkgs#home-manager -- switch --flake ~/.config/home-manager/

# log into github
gh auth login

