#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  gpg-connect-agent killagent /bye
  gpg-connect-agent /bye

  git config --global credential.helper osxkeychain
else
  # install ubuntu packages
  sudo apt install -y $(grep -vE "^\s*#" ~/packages  | tr "\n" " ")

  # install flatpacks
  flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  for i in `cat ~/flatpacks`; do flatpak install flathub $i; done;

  # convox
  if [ ! -f /usr/local/bin/convox ]; then
    curl -L https://convox.com/cli/linux/convox -o /tmp/convox
    sudo mv /tmp/convox /usr/local/bin/convox
    sudo chmod 755 /usr/local/bin/convox
  fi

  # install asdf
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
fi

# ush fish shell
chsh -s /usr/bin/fish

# grab my key from keybase
export KEYID=cdacea52a952f689fda3f401031315d9816c1160
curl https://keybase.io/qnm/pgp_keys.asc?fingerprint=$KEYID | gpg --import

# set up gpg
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# import my key into gpg
echo "$( \
  gpg --list-keys --fingerprint $KEYID\
  | grep pub -A 1 | tail -1 \
  | tr -d '[:space:]' | awk 'BEGIN { FS = "=" } ; { print $2 }' \
  ):6:" | gpg --import-ownertrust;

# ssh via gpg
cat <<EOF > ~/.ssh/config
Host github.com
    IdentitiesOnly yes
    IdentityFile ~/.ssh/id_rsa_yubikey.pub
EOF

# some yubikey bits n pieces
touch ~/.ssh/id_rsa_yubikey.pub
ssh-add -L > ~/.ssh/id_rsa_yubikey.pub
chmod 600 ~/.ssh/id_rsa_yubikey.pub

# load the asdf completions etc.
source ~/.asdf/asdf.sh
source $HOME/.asdf/completions/asdf.bash

# add golang
asdf plugin-add golang
asdf install golang latest
asdf global golang $(asdf latest golang)

# add ruby
asdf plugin-add ruby
asdf install ruby latest
asdf global ruby $(asdf latest ruby)

# add nodejs
asdf plugin-add nodejs
asdf install nodejs latest
asdf global nodejs $(asdf latest nodejs)

# add python
asdf plugin-add python
asdf install python latest
asdf global python $(asdf latest python)
pip install --upgrade pip

# add adr-tools
asdf plugin-add adr-tools
asdf install adr-tools latest
asdf global adr-tools $(asdf latest adr-tools)

# add aws vault
asdf plugin-add aws-vault https://github.com/beardix/asdf-aws-vault.git
asdf install aws-vault latest
asdf global aws-vault $(asdf latest aws-vault)

# add terraform
asdf plugin-add terraform https://github.com/asdf-community/asdf-hashicorp.git
asdf install terraform latest
asdf global terraform $(asdf latest terraform)

# some ruby for neovim
gem install solargraph
gem install neovim

# some python for neovim
pip3 install neovim --upgrade
pip3 install neovim --upgrade

# some node for neovim
npm install -g neovim

# install some extensions for vs code
cat vscode-extensions.txt | xargs -L 1 code --install-extension
