#!/bin/bash

# load the asdf completions etc.
source ~/.asdf/asdf.sh

# add golang
asdf plugin-add golang
asdf install golang latest
asdf global golang $(asdf latest golang)

# add ruby
asdf plugin-add ruby
asdf install ruby latest
asdf global ruby $(asdf latest ruby)

# add nodejs
asdf plugin-add nodejs
asdf install nodejs latest
asdf global nodejs $(asdf latest nodejs)

# add python
asdf plugin-add python
asdf install python latest
asdf global python $(asdf latest python)
pip install --upgrade pip

# add adr-tools
asdf plugin-add adr-tools
asdf install adr-tools latest
asdf global adr-tools $(asdf latest adr-tools)

# add aws vault
asdf plugin-add aws-vault https://github.com/beardix/asdf-aws-vault.git
asdf install aws-vault latest
asdf global aws-vault $(asdf latest aws-vault)

# add terraform
asdf plugin-add terraform https://github.com/asdf-community/asdf-hashicorp.git
asdf install terraform latest
asdf global terraform $(asdf latest terraform)

# add terraformer
asdf plugin add terraformer https://github.com/grimoh/asdf-terraformer.git
asdf install terraformer latest
asdf global terraformer $(asdf latest terraformer)

# aws copilot
asdf plugin add aws-copilot
asdf install aws-copilot latest
asdf global aws-copilot latest

# github cli
asdf plugin-add github-cli https://github.com/bartlomiejdanek/asdf-github-cli.git
asdf install github-cli latest
asdf global github-cli latest

# hasura cli
asdf plugin add hasura-cli
asdf install hasura-cli latest
asdf global hasura-cli latest

# add gcloud
asdf plugin add gcloud https://github.com/jthegedus/asdf-gcloud
asdf install gcloud latest
asdf global gcloud latest
