#!/bin/bash

# load the asdf completions etc.
source ~/.asdf/asdf.sh

# add golang
asdf plugin-add golang
asdf install golang latest
asdf global golang $(asdf latest golang)

# add ruby
asdf plugin-add ruby
asdf install ruby latest
asdf global ruby $(asdf latest ruby)

# add nodejs
asdf plugin-add nodejs
asdf install nodejs latest
asdf global nodejs $(asdf latest nodejs)

# add python
asdf plugin-add python
asdf install python latest
asdf global python $(asdf latest python)
pip install --upgrade pip
