#!/bin/bash

# load the asdf completions etc.
source ~/.asdf/asdf.sh

# some ruby for neovim
gem install solargraph
gem install neovim

# some python for neovim
pip3 install neovim --upgrade
pip3 install neovim --upgrade

# some node for neovim
npm install -g neovim

