name: reviewdog
on: [pull_request, merge_group, push]

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: detect-secrets
        uses: reviewdog/action-detect-secrets@master
        with:
          reporter: github-pr-review # Change reporter.
          github_token: ${{ secrets.GITHUB_TOKEN }}
