name: reviewdog
on: [pull_request, merge_group]

jobs:
  secrets:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }} # no use in dependabot builds
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: detect-secrets
        uses: reviewdog/action-detect-secrets@master
        with:
          reporter: github-pr-review # Change reporter.
          github_token: ${{ secrets.GITHUB_TOKEN }}
